version: 2
jobs:
  build-ios:
    macos:
      xcode: '10.1.0'
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Run secrets script
          command: |
            cd ios
            scripts/setup.sh
      - run:
          name: Bundle Install
          command:  |
            cd ios
            bundle install
      - run:
          name: Run tests
          command:  |
            cd ios
            bundle exec fastlane ios test
      - store_test_results:
          path: "./fastlane/test_output"
      - store_artifacts:
          path: "./fastlane/test_output"
          destination: test_output
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
workflows:
  version: 2
  all:
    jobs:
      - build-ios