platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'News' do
  target 'NewsTests' do
    inherit! :search_paths

    pod 'Nimble'
    pod 'Quick'
  end
end

target 'NewsFramework' do
  inherit! :search_paths
  
  pod 'Moya/RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxSwift'
  pod 'SnapKit'

  target 'NewsFrameworkTests' do
    inherit! :search_paths

    pod 'Nimble'
    pod 'Quick'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
