platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'News' do
  pod 'Sourcery', '~> 0.16.1'
end

target 'NewsFramework' do
  inherit! :search_paths
  
  pod 'Moya/RxSwift', '14.0.0-alpha.1'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxDataSources', '~> 4.0'
  pod 'RxSwift', '~> 5.0'
  pod 'SnapKit'

  target 'NewsFrameworkTests' do
    inherit! :search_paths

    pod 'Nimble'
    pod 'Quick'
  end
end
