fastlane_version "2.105.2"

default_platform :ios

platform :ios do
  desc 'Run tests'
  lane :test do
    scan(
      scheme: 'News',
      devices: ['iPhone 8'],
      clean: false,
      skip_build: true,
      output_types: 'html,junit',
      output_directory: './fastlane/test_output/xctest'
    )
  end

  desc 'Bump build number (CFBundleVersion)'
  lane :bump_build_number do
    increment_build_number
  end

  desc 'Bump major version'
  lane :bump_major_version do
    increment_version_number(bump_type: "major")
  end

  desc 'Bump minor version'
  lane :bump_minor_version do
    increment_version_number(bump_type: "minor")
  end

  desc 'Bump patch version'
  lane :bump_patch_version do
    increment_version_number(bump_type: "patch")
  end

  desc 'Returns a default changelog'
  lane :default_changelog do
    changelog = changelog_from_git_commits(
      between: [ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD~10', 'HEAD'],
      pretty: '* [%h](https://github.com/code8-io/code8-ios/commit/%H) %s (%an)'
    )
    # HAX: strip emoji from changelog
    changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '')
    Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
    changelog
  end
end